# Generated by Django 2.1.4 on 2020-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=16, unique=True)),
                ('bookname', models.CharField(blank=True, max_length=64, null=True)),
                ('origin_bookname', models.CharField(blank=True, max_length=64, null=True)),
                ('writer', models.CharField(blank=True, max_length=64, null=True)),
                ('translator', models.CharField(blank=True, max_length=64, null=True)),
                ('pagenum', models.CharField(blank=True, max_length=8, null=True)),
                ('publishtime', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.CharField(blank=True, max_length=64, null=True)),
                ('content_intro', models.CharField(max_length=512, null=True)),
                ('writer_intro', models.CharField(max_length=512, null=True)),
                ('neededcredit', models.IntegerField(default=-1)),
                ('coverurl', models.CharField(max_length=64, null=True)),
                ('press', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
