# Generated by Django 2.1.4 on 2020-03-05 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=128)),
                ('photos', models.CharField(max_length=128)),
                ('timeouthandle', models.BooleanField(default=True)),
                ('book_sendto', models.IntegerField(default=0)),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_state', models.IntegerField(default=0)),
                ('related_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Book.Book')),
            ],
        ),
    ]
