# Generated by Django 2.1.4 on 2020-03-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bottle', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.User'),
        ),
    ]
