# Generated by Django 2.1.4 on 2020-03-05 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bottle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20, unique=True)),
                ('issuper', models.BooleanField(default=False)),
                ('addresses', models.CharField(default='{"address":[]}', max_length=1024)),
                ('credit', models.IntegerField(default=0)),
                ('enrolldatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isdeleted', models.BooleanField(default=False)),
                ('star', models.ManyToManyField(to='Bottle.Bottle')),
            ],
        ),
    ]
