# Generated by Django 2.1.4 on 2020-03-05 17:14

import Order.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Bottle', '0002_bottle_related_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='acquireOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresscompany', models.IntegerField(default=-1)),
                ('trackingnumber', models.CharField(default='', max_length=64)),
                ('order_state', models.IntegerField(default=0)),
                ('submittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dealtime', models.DateTimeField(blank=True, null=True)),
                ('transactioncode', models.CharField(default=Order.models.get_order_code_ACQU, max_length=32)),
                ('to_address', models.CharField(max_length=256)),
                ('to_name', models.CharField(max_length=64)),
                ('to_phonenumber', models.CharField(max_length=16)),
                ('related_bottle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Bottle.Bottle')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='receiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresscompany', models.IntegerField(default=-1)),
                ('trackingnumber', models.CharField(default='', max_length=64)),
                ('order_state', models.IntegerField(default=0)),
                ('submittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dealtime', models.DateTimeField(blank=True, null=True)),
                ('transactioncode', models.CharField(default=Order.models.get_order_code_RECE, max_length=32)),
                ('from_address', models.CharField(max_length=256)),
                ('from_name', models.CharField(max_length=64)),
                ('from_phonenumber', models.CharField(max_length=16)),
                ('related_bottle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Bottle.Bottle')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='retriveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresscompany', models.IntegerField(default=-1)),
                ('trackingnumber', models.CharField(default='', max_length=64)),
                ('order_state', models.IntegerField(default=0)),
                ('submittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dealtime', models.DateTimeField(blank=True, null=True)),
                ('transactioncode', models.CharField(default=Order.models.get_order_code_RETR, max_length=32)),
                ('to_address', models.CharField(max_length=256)),
                ('to_name', models.CharField(max_length=64)),
                ('to_phonenumber', models.CharField(max_length=16)),
                ('related_bottle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Bottle.Bottle')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
